# 配置在 travis-ci.org 执行自动测试的文件

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# 安装依赖包的命令，例如： pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# 运行测试的命令，例如：python setup.py test
script: tox

# 发布最新版本的包到 PyPI
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: audreyr
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: audreyr/python_boilerplate
    python: 3.8
